on:
  pull_request:
    branches: ['main']

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
